// Code generaTed by fileb0x at "2022-02-12 20:17:49.556047 +0800 CST m=+0.179117584" from config file "b0x.yaml" DO NOT EDIT.
// modified(2022-02-12 19:24:59.284821901 +0800 CST)
// original path: swagger-ui/dist/swagger-resources-test

package swaggerFiles

import (
	"os"
)

// FileSwaggerResourcesTest is "/swagger-resources-test"
var FileSwaggerResourcesTest = []byte("\x5b\x7b\x22\x6e\x61\x6d\x65\x22\x3a\x22\x64\x65\x66\x61\x75\x6c\x74\x22\x2c\x22\x75\x72\x6c\x22\x3a\x22\x2f\x76\x33\x2f\x61\x70\x69\x2d\x64\x6f\x63\x73\x22\x2c\x22\x73\x77\x61\x67\x67\x65\x72\x56\x65\x72\x73\x69\x6f\x6e\x22\x3a\x22\x33\x2e\x30\x2e\x33\x22\x2c\x22\x6c\x6f\x63\x61\x74\x69\x6f\x6e\x22\x3a\x22\x2f\x76\x33\x2f\x61\x70\x69\x2d\x64\x6f\x63\x73\x22\x7d\x5d")

func init() {

	f, err := FS.OpenFile(CTX, "/swagger-resources-test", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileSwaggerResourcesTest)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
